### ISSUE TITLE
Exception in thread Thread-2:

### ISSUE THREAD

**Issue by ZhengLiJing** [dibrale/samist#1]
Hello, Dear author, I met this error below，How can I fix that? 
I use mac pro, python3.8 to run this。

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xx/Library/Python/3.8/lib/python/site-packages/PySimpleGUI/PySimpleGUI.py", line 11815, in _long_func_thread
    return_value = original_func()
  File "./main.py", line 266, in <lambda>
    lambda: segmentation(points_per_side, min_area, stability_thresh, predict_iou),
  File "./main.py", line 58, in segmentation
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
  File "/Users/xx/Library/Python/3.8/lib/python/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/Users/xx/Library/Python/3.8/lib/python/site-packages/segment_anything/build_sam.py", line 66, in _build_sam
    sam = Sam(
  File "/Users/xx/Library/Python/3.8/lib/python/site-packages/segment_anything/modeling/sam.py", line 46, in __init__
    self.register_buffer("pixel_mean", torch.Tensor(pixel_mean).view(-1, 1, 1), False)
TypeError: register_buffer() takes 3 positional arguments but 4 were given
<img width="432" alt="image" src="https://github.com/dibrale/samist/assets/23631850/592e1158-a596-4503-82b3-e16539188419">

**Comment by dibrale** [comment]
Hello @ZhengLiJing,

Thank you for using SAMIST and letting me know about your issue. There are a couple of things we should check. Here they are in order of how likely they are to be helpful:

**1.** Does your SAM checkpoint match the model type selected? Make sure your selected model type (vit_h) corresponds to the checkpoint file you are using.
**2.** I recently updated the requirements file for the project to cover potential missing dependencies. Try updating the 'requirements.txt' file on your end with the latest one in the repository and running `pip install -r requirements.txt` again.
**3.** While Meta's SAM package is supposed to work on python >= 3.8, I am using Python 3.10.9 to run SAMIST. You can try using the same or higher version of Python to see if this fixes your issue.

If your issue persists despite these steps, please download and run the latest version of the script and include the error message again so that your stack trace refers to the same line numbers I am presently looking at. This will help me work on your issue.

**Comment by dibrale** [comment]
Closing old issue. Feel free to let me know if you are still having problems.
