### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by JCGoran** [dibrale/samist#2]
I'm getting this while running in a fresh venv:

```plaintext
Traceback (most recent call last):
  File "/samist/main.py", line 14, in <module>
    from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
  File "/samist/env/lib/python3.9/site-packages/segment_anything/__init__.py", line 7, in <module>
    from .build_sam import (
  File "/samist/env/lib/python3.9/site-packages/segment_anything/build_sam.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

Traceback (most recent call last):
  File "/samist/main.py", line 14, in <module>
    from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
  File "/samist/env/lib/python3.9/site-packages/segment_anything/__init__.py", line 14, in <module>
    from .predictor import SamPredictor
  File "/samist/env/lib/python3.9/site-packages/segment_anything/predictor.py", line 14, in <module>
    from .utils.transforms import ResizeLongestSide
  File "/samist/env/lib/python3.9/site-packages/segment_anything/utils/transforms.py", line 10, in <module>
    from torchvision.transforms.functional import resize, to_pil_image  # type: ignore
ModuleNotFoundError: No module named 'torchvision'
```

While it seems to be an upstream issue, after installing both `torch` (version `2.0.1`) and `torchvision` (version `0.15.2`) it seems to work fine.

**Comment by dibrale** [comment]
Thank you for bringing this to my attention. I've updated the repo with a list of requirements that I generated automatically and pruned a bit, which should hopefully prevent this and similar issues for others. I'm closing this issue for now since it seems to be solved, but please let me know if you encounter any other difficulties.
